
" Windows specific, use NMake
set makeprg=nmake
"set makeprg=nmake\ /f\ misc\\Makefile\ /nologo

function! s:MSBuild()

	" Dont wait for key press
	cd misc
	"silent make -f misc\Makefile -nologo
	silent make -nologo
	cd ..

	" Id of the last window (num windows)
	let numWindows=winnr('$')

	copen

	" Create at least a vertical split
	if numWindows < 2

		" Go to quickfix and move it to far right
		wincmd L

	else

		" Move quickfix window to top if at bottom
		if winnr() == winnr('$')
			wincmd x
		endif

	endif

endfunction

function! s:MSDebug()
	silent make rundebug
endfunction

" Custom mappings
nnoremap <leader>b :call <SID>MSBuild()<cr>

" Build solution on <F7>
nnoremap <F7> :call <SID>MSBuild()<cr>


