version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
matrix:
  - fast_finish: true
build:
  project: Zork.sln
  verbosity: minimal
